🐞 fix: cookie_to_dict exception
原来的方式会提示
```
ValueError: dictionary update sequence element #4 has length 1; 2 is required
```
python 3.10